#!/bin/bash

# entire script fails on any error in code the code
set -o errexit

#exit if any pipe command fails
set -o pipefail

#exits if any variable is not set
set -o nounset

postgres_ready() {
python << END
import sys
import psycopg2
try:
    psycopg2.connect(
        dbname="${DB_NAME}",
        user="${DB_USER}",
        password="${DB_PASSWORD}",
        host="${DB_HOST}",
        port="${DB_PORT}"
    )
except psycopg2.OperationalError:
        sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
 >&2 echo "Database loading.."
 sleep 1
done
>&2 echo "Database Ready!"

exec "$@"